uploads = []
generated = []

[[outputs]]
id = "u8X75kP_N4hTYPdYVic17"
uri = "file://xquare-club-netlify.tar.gz"
type = "unspecified"
title = "XQUARE CLUB - Complete Built Website (HTML + CSS + JS + Images)"

[[outputs]]
id = "HTEEPlNDNvdnmrbU1X9xY"
uri = "file://xquare-club-source-code.tar.gz"
type = "unspecified"
title = "XQUARE CLUB - Full Source Code"

[[outputs]]
id = "rjI-HMzJ7Xw-GSQ3LFyp_"
uri = "file://xquare-club-website.tar.gz"
type = "unspecified"
title = "XQUARE CLUB - Website (Fixed - Opens in Browser Directly)"
